# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Silky Pets
email: contact@silkypets.com
description: > # this means to ignore newlines until "baseurl:"
  Find the best life tips, products, and accessories to make your pet the happiest and for you to become a proud and happy owner.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://silkypets.com" # the base hostname & protocol for your site
twitter_username: DaveGomez
github_username:  davegomez

# Build settings
markdown: kramdown
